### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by GATETE2**
This is a README.md created to clearly explain what was done during phase 2&3 it also includes contents details of what was pushed in our GitHub repository

### CODE REVIEW

**Comment by GATETE2** [comment]
Find the README.md created

**Comment by daniel-habimn** [comment]
I think on Phase 2 about Descriptions and Diagram are well done and its summary

**Comment by Adol1329** [comment]
Implemented the logical model design for ARMS with entities like students, courses, enrollments, instructors, and grades, ensuring proper relationships, keys, and constraints.

**Comment by cyizasabine** [comment]
I think this phase 2 and 3 has good core structure and are well understandable , Good coverage of core academic management functionality and Clear definition of objectives and expected outcomes.

**Comment by Karbecca** [comment]
BPMN diagram clearly outlines the process flow for student registration, course management, enrollment, and grade input, showing effective collaboration between departments and logical decision points.

**Comment by Karbecca** [comment]
Everything looks Great!!!

**Comment by Manzidarius** [comment]
This is a great work. phase 2 and three are well understood

**Comment by Hakizimana12** [comment]
everything looks good so far

**Comment by Rhodin1** [comment]
Perfect! Let's continue with other phases

**Comment by Hakizimana12** [comment]
Good

**Comment by cyizasabine** [comment]
Looks perfect

**Pull request merged**
